### ISSUE TITLE
Failing test on proposal in the datagrid

### ISSUE THREAD

**Issue by ahocquard** [akeneo/pim-community-dev#10083]
https://circleci.com/gh/akeneo/pim-enterprise-dev/8924#tests/containers/7

See screenshot. A value is missing in price value.

tests/legacy/features/pim/work-organization/workflow/proposal/display_proposal_in_datagrid.feature:15

**Comment by BitOne** [comment]
Maybe this issue should be moved in pim-enterprise-dev ;)

**Comment by ahocquard** [comment]
We choosed to keep one repository, easier to follow things.

**Comment by BitOne** [comment]
Oh okay, I didn't see the CI tag. All clear, thanks @ahocquard !

**Comment by mmetayer** [comment]
I guess the issue comes from here: https://github.com/akeneo/pim-enterprise-dev/blob/79e4c95a7c1ea38516115cc962cdc17f844e650c/src/Akeneo/Pim/WorkOrganization/Workflow/Bundle/Datagrid/Normalizer/ProductProposalNormalizer.php#L49, because the raw values do not contain empty values anymore (BTW a similar test with a scalar value would fail in 3.1 as well)
I don't get why we normalize the values in `changes` key, whereas the changes are already well computed in `EntityWithValuesDraftInterface::getChanges()`
