### ISSUE TITLE
3.2.9 - Saving view in product-grid doesn't save filters

### ISSUE THREAD

**Issue by jcpla** [akeneo/pim-community-dev#10812]
Hi,

I've tested to save a new view in the main product-grid in http://demo.akeneo.com/#/enrich/product/

The columns are saved, but the filters at the left are not if I select new attributes.

**Comment by Doodoune** [comment]
For me, it's working well.

On http://demo.akeneo.com/#/enrich/product/ - with the view "test_elo" and my attribute "test_elo".
Warning, our demo env will be reset every hour at 42min.

Could you explain me step by step what was your test?

**Comment by jcpla** [comment]
Hi doudoune,
I've tried again but can't.

1) I go on http://demo.akeneo.com/#/enrich/product/,
2) Add a new filter (eg. test_elo) + click on Done button
3) Create new view => save
4) The view is created but there are still the default filters.

I've flushed my cache to be sure and test on chrome and firefox

**Comment by Doodoune** [comment]
Hi jcpla,

So this is normal, it only saves the filter "activated" (that have a value on it) - The default value of a filter is "all". So it doesn't filter anything. So when you create a view it doesn't "save" this filter because it doesn't filter anything :)

If you add value to your filter, and then you create your view, it will work.

Regards,

**Comment by jcpla** [comment]
ok I understand.
Thanks for the reply
Have a nice day
