### ISSUE TITLE
PIM community docker in production

### ISSUE THREAD

**Issue by vincentvanderwalt** [akeneo/pim-community-dev#11044]
Good afternoon.

I'm trying to figure out why PIM should not be run as a docker image in production. I can't find any information other than it saying the current docker images are for dev test only.

I tried raising the question by following the link below but that link redirects to root of www.akeneo.com and doesn't open the forum.

_**Please submit your question via the forum https://www.akeneo.com/forums/forum/programming-questions/**_

Can someone please explain why PIM community edition cannot be run in docker as part of a production environment ?

Any help appreciated.

**Comment by Doodoune** [comment]
Hi @vincentvanderwalt,

You could totally run your docker in production but we advise to not use the dev docker image because it's is designed for dev (with XDEBUG for example, not useful in production).

We do not provide a fully ready Docker production image. 

But in 4.0, we provide our own "base image" to build your own Docker production image: https://hub.docker.com/r/akeneo/pim-php-base

Hope it will help you.

Regards,

**Comment by jmleroux** [comment]
Closed, feel free to reopen it if needed.
Regards

**Comment by nelmfinda** [comment]
> 

Hi @Doodoune @jmleroux where I can see the Dockerfile of this image? Thanks!
