### ISSUE TITLE
Export records without categories

### ISSUE THREAD

**Issue by Philippe-M** [akeneo/pim-community-dev#17500]
:bug:
Hello everyone, when I export product sheets in csv (exportFullArticles), the sheets not assigned to a category are not exported. While in the export settings I have selected "All products".
:bug:

:paperclip: Akeneo CE 5.0.96 :paperclip:

![image](https://user-images.githubusercontent.com/4558101/180177471-28e99594-1f32-432c-9675-736f71654901.png)

**Comment by timonburkard** [comment]
Hi @Philippe-M,

Unfortunately this is by design. See [documentation](https://help.akeneo.com/pim/v6/articles/product-export-builder.html#filter-on-categories):

![image](https://user-images.githubusercontent.com/54314495/181018117-4afd5d9d-99e3-4a30-a579-8f2b979de3b0.png)

I am in discussion with Akeneo Support Team (we have an enterprise licence) about that issue and they opened an internal improvement ticket to investigate.

**Comment by Philippe-M** [comment]
Ok thank's
