### ISSUE TITLE
Type Error in ResetIndexesCommand.php

### ISSUE THREAD

**Issue by Rafelder** [akeneo/pim-community-dev#19430]
:bug: **I'm reporting a Bug** :bug:

There is a type error in the ResetIndexesCommand.php:

https://github.com/akeneo/pim-community-dev/blob/ece09fc0bf26168d6a6fa56bbd34786c17e030f2/src/Akeneo/Tool/Bundle/ElasticsearchBundle/Command/ResetIndexesCommand.php#L44-L50

```
CRITICAL  [console] An error occurred while using the console. Message: "Symfony\Component\Console\Command\Command::addOption(): Argument #2 ($shortcut) must be of type array|string|null, bool given, called in /app/vendor/akeneo/pim-community-dev/src/Akeneo/Tool/Bundle/ElasticsearchBundle/Command/ResetIndexesCommand.php on line 49"
```

The error prevents the console to be used without a command and prevent the use of the command `akeneo:elasticsearch:reset-indexes` completely.

Steps to reproduce:
- Setup a new Akeneo (in my case CE 7.0.10)
- Call "bin/console" without a command or call the command `akeneo:elasticsearch:reset-indexes`

I cant provide a system file, because the system page needs functioning ElasticSearch nodes and the bug prevents reseting the nodes.

**Comment by Rafelder** [comment]
The same error occurs in the following commands:

- `vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductCommand.php `
- `vendor/akeneo/pim-community-dev/src/Akeneo/Pim/Enrichment/Bundle/Command/IndexProductModelCommand.php`
- `vendor/akeneo/pim-enterprise-dev/src/Akeneo/Pim/WorkOrganization/Workflow/Bundle/Command/IndexProductProposalCommand.php`

**Comment by jmleroux** [comment]
Hello @Rafelder ,

Didn't you upgrade your Symfony version in `vendor`?

Because CE PIM requires Symfony 5.4, and we can see that the `addOption` shortcut is not typed in this version [here](https://github.com/symfony/symfony/blob/5.4/src/Symfony/Component/Console/Command/Command.php#L457)

You're stil right about the type issue, but it should not throw error because it's only PhpDoc type on SF 5.4.

Yet, we will have an issue if upgrading to Symfony 6.0+, because the [shorcut will be typed](https://github.com/symfony/symfony/blob/6.3/src/Symfony/Component/Console/Command/Command.php#L487)

**Comment by Rafelder** [comment]
I installed a fresh copy of Akeneo 7.0.10 (with smyfony 5.4) when the errors occured. I checked the typings of the addOption function and can confirm that the typing is only done in PhpDoc. I don't know why the critical errors occured in my case but they are gone now.

I guess the issue can be closed. Thank you.

**Comment by DanieliMi** [comment]
This is still an issue in [v7.0.19](https://github.com/akeneo/pim-community-dev/releases/tag/v7.0.19). When is this expected to be released in a Tag?
