### ISSUE TITLE
Cannot import number attributes with decimals

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#3348]
I cannot find a way to import attributes of the type `pim_catalog_number` with decimals in Akeneo 1.4.1.

When I try to add a new column with the title `decimalsAllowed` (as in the old `attributes.yml`) in `attributes.csv`, I get this error during the installation:

    STEP pim_connector.jobs.csv_attribute_import.import.title WARNING on item { type:pim_catalog_number, code: IDENT, label-de_DE: ‘Identifier (automatisch)’, label-en_US: Identifier, group: general, decimalsAllowed: ‘0’, unique: ‘0’, useable_as_grid_filter: ‘0’, allowed_extensions: ”, metric_family: ”, default_metric_unit: ”, reference_data_name: ”, localizable: ‘0’, scopable: ‘0’ }:
    decimalsAllowed: This value should be of type bool.: 0

When I create manually a number with decimals in Akeneo, the `decimalsAllowed` column gets also not exported.

(I have already asked the same question in the [Forum](http://www.akeneo.com/forums/topic/akeneo-v-1-4-0-rc1-decimalsallowed/) two weeks ago for Akeneo 1.4 RC1, but nothing changed in the final release.)

**Comment by solivier** [comment]
Hi Hocdoc,

In fact yes it is possible, instead of using the column name “decimalsAllowed” you have to use “decimals_allowed” in the attributes.csv file in order to be able to import products with decimal values.
The old system was very permissive and it allowed the two values, in order to keep a consistent file format we now use only not “camel case” for column name.

Hope it helped
Do not hesitate if you have further questions :)

Cheers,
Olivier.

**Comment by Hocdoc** [comment]
Thanks, that worked :-).
