### ISSUE TITLE
Web service usage

### ISSUE THREAD

**Issue by sagikazarmark** [akeneo/pim-community-dev#3421]
Looking at the WebService: it is quite simple for now. Do you plan to improve it? Add catregory listing for example? (Do you accept PRs? If so: it would be good to have a roadmap or planned services)

Also a question: Do you think it is a good idea to use WebService from Akeneo instead of exporting data from it and importing in an ecommerce site? My plan is to add Varnish in front of it so products are being cached for a while. This way I only need an API client and don't need to store proudcts in a custom database.

**Comment by nidup** [comment]
We plan to improve the web API (to add read and write methods) but we don't have ETA for now.
We welcome any Pull Requests on bug fixes and are available to discuss on feature requests.
If you want extend the web API, you can do it in a custom bundle (that you can release in a dedicated repository on github, i'm pretty sure that a lot of other developers can be interested by this improved API :) ).

I would not use the webservice API for that, even with a proxy cache, because it exposes your PIM to various attacks and issues, I would use standard csv export and if you need to store the data in a custom table, you can create a cron and import exported data with a "load data infile" to have a really performant synchronization https://dev.mysql.com/doc/refman/5.1/en/load-data.html

**Comment by sagikazarmark** [comment]
Actually I agree with you that exposing PIM to the outside world is not a good idea. Probably this solution is bit slower as well than using a database. However in some cases it is simply easier. To lower the risk, some limitations could be set. Apart from that, what other issues might appear?

**Comment by sagikazarmark** [comment]
Further thinking about this: I think I don't get the whole idea behind this.

Am I supposed to duplicate the whole PIM database in my ecommerce site to fully make it working?

Also, this load data infile solution is a bit vague for me. It suggests that my database structure must follow the CSV files structure.

**Comment by nidup** [comment]
Sorry, I guess i misunderstood your point, if you've an existing ecommerce website, the idea is to use the export system of the PIM then import the data in your ecommerce website (there are existing connectors for Magento, Drupal, etc and you can create your own).

I though that you wouldn't import these data in your website and you would use the akeneo web api to directly build ecommerce pages from these api calls and use varnish to limit the PIM overload, in this case only, i would suggest to create a dedicated synchronized table (via load infile) and use it to build your pages content.
