### ISSUE TITLE
No ability to change precision of "number" fields

### ISSUE THREAD

**Issue by mathielen** [akeneo/pim-community-dev#3763]
Why is a number-typed attribute always shown with 4 decimal places? Even if I set the field to not allow decimals, it is still shown as it would be allowed.

Thought it might be related to the precision argument in the constructor of Pim\Bundle\TransformBundle\Normalizer\Flat\ProductValueNormalizer.

Any way to have the precision as a configuration value? Or at least not to show decimal places if they are not allowed?

Thanks!

**Comment by LaureBro** [comment]
Hello, 
Currently the system records the number with .0000 even if you do not allow decimals in the attribute properties.
Please note that the validation on decimals works well.

This behaviour will be fixed in the next Akeneo version (1.5) that will be released beginning of next year.

Best regards,

Laure

**Comment by mathielen** [comment]
Great! Thank you.
