### ISSUE TITLE
admin access issue

### ISSUE THREAD

**Issue by harshavmb** [akeneo/pim-community-dev#3770]
Hi,

I logged into http://demo.akeneo.com/ with admin/admin credentials. I could create a user without admin privileges, I logged in with newly created user credentials (harshavmb - username).

However, without admin privileges I could delete admin user. Later I recreated the admin user so that others will not face the issue.

So, to conclude access privileges are not working properly on demo application. Could you please fix this?

**Comment by LaureBro** [comment]
Hello, 

Actually the permissions are the same for the 3 roles on our demo.akeneo.com environment, so that's why you could delete an admin with a user role. It's not a bug, it's a configuration "issue". 
We're planning to change this, because as you have noticed it does not reflect the capabilities of Akeneo.
You can make a test in System/Users management/Roles and Edit the permissions for the User role. Remove permissions on System for instance, log back into the system with the user, and you will not have access anymore to the System menu.

Best regards, 

Laure

**Comment by harshavmb** [comment]
sure.. Thanks LaureBro
