### ISSUE TITLE
1.4.18 Add attribute in product form

### ISSUE THREAD

**Issue by alexisfroger** [akeneo/pim-community-dev#3958]
Hi,

I just moved on the 1.4.18 version. When I am in the product form and I click on the "add attribut" button I have a code message like this picture. Is it normal ? 

![image](https://cloud.githubusercontent.com/assets/15442639/12743484/77bef9b8-c98e-11e5-8f3f-1534b69cb0c3.png)

**Comment by LaureBro** [comment]
Hello Alexis, 

It's a French translation missing, it will be implemented with the next patch.
It's not normal but it happens sometimes, since we rely on Crowdin to translate the French wording, we can have a small delay before translations appear.
(If you want to participate to Akeneo's translations, here's the link to our Crowdin project: https://crowdin.com/project/akeneo)

Best regards, 

Laure

**Comment by alexisfroger** [comment]
Thank you for your answer. I will look your Akeneo's translations project !

**Comment by alexisfroger** [comment]
Hey,

I updated on the 1.4.20 version. I always have the same error message ! Have you fixed this bug ?

Alexis

**Comment by LaureBro** [comment]
Hello Alexis, 

Yes, it should have been fixed, but we got an issue with our script. I'll keep you updated.

Best regards, 

Laure

**Comment by willy-ahva** [comment]
Bug has been fixed in 1.4.22. Thanks for the feedback !
