### ISSUE TITLE
Products get auto-enabled during CSV import

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#3990]
After updating disabled products with the CSV product import they get automatically enabled. The CSV doesn't contain  an `enabled` column.
 
I would expect that the product status stays the same when the `enabled` column is missing.

**Comment by LaureBro** [comment]
Hello Hocdoc, 

Yes, if no information is added to the import file, the products' statuses will not be kept. Adding a column 'enabled' in your import file, even empty will make sure that statuses are kept.

This system will be improved in the 1.5.

Best regards,

Laure

PS: which PIM version are you using: 1.3 or 1.4?

**Comment by Hocdoc** [comment]
Ok, thanks for your information. (Although I think the import should keep the products statuses.)
I'm using 1.4.19.

**Comment by julienanquetil** [comment]
Same thing here in 1.3.38

**Comment by LaureBro** [comment]
Hello Hocdoc, 

We understand it's not the ideal way to manage this, but since it has always been working this way, changing this behaviour could impact many customers or users... 
That's why it has been changed in the 1.5, and not been patched before.

What you can do if you are using a standard import is to override the class Pim\Bundle\BaseConnectorBundle\Processor\ProductProcessor to get the desired behaviour: 

    protected function transform($item)
    {
        // new version
        return $this->transformer->transform($this->class, $item, []);
        // standard version
        // return $this->transformer->transform($this->class, $item, array('enabled' => $this->enabled));
    }

This code is for the 1.3 but it should also work for the 1.4. 

If the column is not in the import file, the current product status will be kept. New products will have the status 'enabled'.

**Comment by Hocdoc** [comment]
Thanks for the source patch!
I'm already curious about 1.5.
