### ISSUE TITLE
Locale specific

### ISSUE THREAD

**Issue by tonongregory** [akeneo/pim-community-dev#4120]
Reported in 1.4.20
Tested on Akeneo PIM online demo.

Attributes flaged as "Locale Specific" are never exported.

In normalization process the following filter is applied

> protected function filterLocaleSpecific(ProductValueInterface $value)
>     {
>         /** @var AttributeInterface $attribute */
>         $attribute = $value->getAttribute();
>         if ($attribute->isLocaleSpecific()) {
>             $currentLocale = $value->getLocale();
>             $availableLocales = $attribute->getLocaleSpecificCodes();
>             if (!in_array($currentLocale, $availableLocales)) {
>                 return true;
>             }
>         }
>         return false;
>     }

But `$value->getLocale()` always return null
Visibly value locale is never saved in database.

**Comment by LaureBro** [comment]
Hello, 

You are right, locale specific attributes do not seem to be exported. 
I have informed and created a ticket so our development team fixes it.
I cannot give you an estimated time of resolution, but we'll let you know when the bug will be fixed.

Best regards, 

Laure

**Comment by nidup** [comment]
internal ticket number PIM-5639

**Comment by a2xchip** [comment]
@nidup If I want to create PR to this ticket should i checkout from 1.4 branch?

**Comment by nidup** [comment]
Hi @a2xchip !

Depends on which version you need it :smile: 

When an issue is raised by one of our customer using the Enterprise Edition, we fix it in the context of  our paying support and we release the patch on the affected version (if the bug concerns the community edition on which the enterprise edition relies, everybody benefits of the fix).

For issues raised directly on the Community Edition, we usually fix only on master because there is less limitations on authorized BC Breaks and also a lot less work to merge / apply the patch on every more recent version.

**Comment by a2xchip** [comment]
@nidup :smile: :smile: 

Ok! I'll PR it branching from master ) 

I mentioned you marked it for 1.4 milestone because of that i was asking it.

Pls assign me on this issue cause there was accidental PR duplications this week, and I lost one night debugging and fixing bug that was already fixed by @willy-ahva 

Thank you very much! An sorry for such late night qiestions ;)

**Comment by nidup** [comment]
Too bad for the PR duplication, so sorry :(

This issue may come from the fact that we have an internal Jira for paying support + Github issues for community support. We need to double think about this and find a way to avoid the risk of work duplication. Maybe a script to synchronize issues or something like that.

No pb for the questions, always happy to discuss ;)

**Comment by a2xchip** [comment]
@nidup yes, unfortunately it caused because github doesn't tracks jira tickets mentioning. It will be good to have such script syncync jira and github even once per hour

**Comment by pierallard** [comment]
https://orly-appstore.herokuapp.com/generate?title=Work%20at%20night&top_text=A%20unreadable%20book&author=Nicolas%20Dupont&image_code=3&theme=10&guide_text=The%20complete%20guide&guide_text_placement=bottom_right

**Comment by nidup** [comment]
@pierallard @a2xchip i'm not the only one to work at night ;) have a good night guys!

**Comment by a2xchip** [comment]
@nidup Thank you :+1:

**Comment by damien-carcel** [comment]
Hello @a2xchip . Did you have time to work on this issue? It is next to be fix in our JIRA backlog, and I was about to work on it when I realized you wanted to do it. If you are still working on it, then I will keep the JIRA ticket on hold.

Thanks a lot for all your contributions by the way :).

Regards,
Damien

**Comment by a2xchip** [comment]
@damien-carcel Hello! I'm still working on it. Unfortunately i have very few free hours last weeks. Please keep it on hold for about one more week. Thank you!

**Comment by damien-carcel** [comment]
No problem, take your time :).

**Comment by LaureBro** [comment]
Hello @a2xchip, 

Just to let you know we really need this issue to be fixed, so we will work on it on our side.
Did you already create a PR or find some possible solution that could help us?

Thanks a lot!

Laure

**Comment by nidup** [comment]
Hi @tonongregory 

This :bug: has been fixed in the upcoming v1.6.0, will release it in a couple of weeks :tada: 

Have a good day!
