### ISSUE TITLE
Uncomplete export of attributes properties

### ISSUE THREAD

**Issue by a2xchip** [akeneo/pim-community-dev#4220]
Attribute export doesn't exports custom type's properties. For example attribute typed as pim_catalog_price_collection doesn't export 'decimalsAllowed' property to csv.

**Comment by nidup** [comment]
Hi @a2xchip 

Thank you for the report !
You're right, we should always export all attribute properties we're able to import.
A core dev also raised the following issue to our Product Owner,
```
IM-465 : Export attributes: all importable columns are not exported
For example, these columns were not exported:
max_characters
number_min
number_max
decimals_allowed
negative_allowed
max_file_size
... maybe there is another ones.
```
Could you be interested to add these missing columns?

If interested thank you to read and sign the following contributor agreement https://www.akeneo.com/contributor-license-agreement/

To do so, we need to add fields them here https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/TransformBundle/Normalizer/Structured/AttributeNormalizer.php#L56

PS: an upcoming PR https://github.com/akeneo/pim-community-dev/pull/4213 that will merge next week will move this class in the catalog component because the structured normalized data is our standard format, we're trying to use it everywhere.

**Comment by a2xchip** [comment]
@nidup I already signed i contributor agreement. Is it better to fix it after #4213 or there is no difference?

**Comment by nidup** [comment]
I don't find your github username in agreement responses (maybe a typo or a issue with our form), could you re-fulfill it please?
No difference, we can fix in same time, we'll just maybe have to rebase the second PR that will merge :)

**Comment by a2xchip** [comment]
@nidup Ok! No problem :-)

**Comment by nidup** [comment]
Thank you, I checked it's ok now :+1:

**Comment by a2xchip** [comment]
Hello!
@nidup https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Component/Catalog/Normalizer/Structured/AttributeNormalizer.php Is our target here now?

**Comment by a2xchip** [comment]
Attribute export table became bigger, but we can export more fields if needed. @nidup Is there list of fields in IM-465?

**Comment by Delphineray** [comment]
Hello @a2xchip 

Thank you Alexander for your contribution.
I am product owner in the Akeneo product team, hereafter the list of all the attributes properties missing in the attributes export:
- available_locales
- max_characters
- validation_rule
- validation_regexp
- wysiwyg_enabled
- number_min
- number_max
- decimals_allowed
- negative_allowed
- date_min
- date_max
- max_file_size
- minimum_input length

Delphine

**Comment by a2xchip** [comment]
Hello @Delphineray ! Thx, for your reply! Given commit implements only:
* wysiwyg_enabled
* number_min
* number_max
* decimals_allowed
* negative_allowed

Because We personally met need of these in our implementation.

Is it better to complement the remaining and PR them all? These are not yet implemented: 

* available_locales
* max_characters
* validation_rule
* validation_regexp
* date_min
* date_max
* max_file_size
* minimum_input length

**Comment by willy-ahva** [comment]
Hi @a2xchip ! Always a pleasure to see a new contribution, thank you very much for it ! It would be nice to complete the same PR. In this way we'll have to launch only once all tests on our Continuous Integration and results will be render faster.
Don't hesitate to ping me on your PR when code will be completed and I'll manage to run all tests for you. Same if you have a question, ping me ;)

Best regards,
Willy

**Comment by a2xchip** [comment]
@willy-ahva Thank you! I plan to complete it this evening and will ping on update.

**Comment by a2xchip** [comment]
@willy-ahva Ping :8ball:

**Comment by nidup** [comment]
@Delphineray the enhancement has been merged :tada: we'll deploy it next week on test-dev envs :dancer:
