### ISSUE TITLE
product DatagridView - don't saves filters

### ISSUE THREAD

**Issue by userz58** [akeneo/pim-community-dev#4295]
http://demo.akeneo.com/enrich/product/
1. i select my list of columns
2. i select fileds for filter
3. i click 'Create View' and save it.
when i will selecting other saved view, my saved filter fileds will not be restored.
always loads standart filter fields set

**Comment by userz58** [comment]
![filters](https://cloud.githubusercontent.com/assets/2612186/14302271/c4999be4-fba7-11e5-8e19-c6abe007fd1a.jpg)

**Comment by a2xchip** [comment]
Confirm same for 1.4 we have

**Comment by willy-ahva** [comment]
Hi guys !

Thank you for your feedback ! We'll try to reproduce and then add this potential bug in our internal bug reporter.

Regards,
Willy

**Comment by LaureBro** [comment]
Hello, 

Filters that are empty or matching 'ALL' are not saved, the system considers that they are not active filters. Was it your case?

Best regards, 

Laure

**Comment by Hocdoc** [comment]
May be the same issue as  #3592

**Comment by a2xchip** [comment]
@Hocdoc Seems so. 

@nidup If filter managing really relates on Akeneo's source and not on Oro may be you can point me and i will be able to fix it and PR?

**Comment by juliensnz** [comment]
Hello guys,

For now it's not a bug. Let me explain why:

Views are ment to save the result of the grid. They are not ment to save the current filter selection. That's why, when you add filters without changing the default value of the filter, you don't get them back when changing the view.

We have a lot of complains about this feature and I understand the confusion. We already have a ticket in our backlog (IM-139) to fix this.

I will keep you updated on this subject as soon as we prioritise it !

regards,

Julien

**Comment by juliensnz** [comment]
I closed the issue because it was a duplicated of https://github.com/akeneo/pim-community-dev/issues/4295

**Comment by a2xchip** [comment]
It was #4295 :1234: @juliensnz

**Comment by userz58** [comment]
@juliensnz
>> Views are ment to save the result of the grid. They are not ment to save the current filter selection. 
no, it bug for early version ORO.
at last versions all works good

**Comment by a2xchip** [comment]
@userz58 May you provide link with ORO fixes?
