### ISSUE TITLE
Cannot remove selected value in product grid filter

### ISSUE THREAD

**Issue by s0ps** [akeneo/pim-community-dev#4356]
Akeneo Version 1.5.1
After searching by Simple Select filter in product grid it is impossible to remove previously selected value.

**Comment by a2xchip** [comment]
@s0ps Can you explain it more?

**Comment by s0ps** [comment]
For example in your demo: http://demo.akeneo.com/
If you add Brand filter to filters and filter by Canon and then it is impossible remove the selected Canon option from filter.

**Comment by a2xchip** [comment]
@s0ps See it! Selected options disappears after selection. Seems it is UI bug.

**Comment by a2xchip** [comment]
@jjanvier @juliensnz I can reproduce it. As I understand the problem is in ```select2-choice-filter.js```.

First thoughts were that bug relates to dinamically added filters only. But if we do try the same on Group which is default it will act in the same way. But not the family filter. 

In case of family ```<ul class="select2-choices">``` is updated with  ```li>selected-value+li>input```
But in case with groups and brands not.

**Comment by LaureBro** [comment]
Thanks a lot @a2xchip!

**Comment by nidup** [comment]
cf PR comments.
