### ISSUE TITLE
Behat test optimization

### ISSUE THREAD

**Issue by a2xchip** [akeneo/pim-community-dev#4359]
**I'm asking a Question**

Hello guys!

I'm curious if anybody checked if PIM has the same behat optimization issues Sylius revealed: http://lakion.com/blog/how-did-we-speed-up-sylius-behat-suite-with-blackfire? Are there any steps in this direction?

**Comment by aRn0D** [comment]
hi @a2xchip,

We had a look to this post which is really interesting (some guys in our team already worked on Sylius too). Our Behat architecture is based on Behat2 and needs to be re-factored. We discussed a lot about this topics since fews weeks  because we want to reworked it. Stay tuned, we will give you feedback!

**Comment by a2xchip** [comment]
@aRn0D It is cool! Cause it is hard to run all PIM tests and even single module. I checked sylius master result on my machine it takes 25min.
