### ISSUE TITLE
Memory leaks in 1.5 and ways to reduce memory usage

### ISSUE THREAD

**Issue by NovikovViktor** [akeneo/pim-community-dev#4416]
Hello everyone, I have faced with performance and memory leaks issues while importing file with about 70k of products.

So during short investigation I found that following option might speed up Akeneo import:
1) Use `gc_collect_cycles` in `ProductSaver -> saveAll()`. After saving each batch of products (100) about 4k of refs were cleared.
2) Remove some data from Doctrine identity map. Actually it looks like Doctrine clear it somehow by itself, but when I added this `$this->objectManager->clear('Pim\Component\Catalog\Model\Product');` to 
`ProductSaver -> saveAll()` it saved about 0.25 Mb of memory.
3) And this one is the most interesting: method findOrCreateProduct(), searches through `product_value` table for `product identifier`, and then searches for appropriate product id in `product` table. This is quite heavy operation. So, to fix this we created `identifier__product_id _map` table, indexed by `identifier`. It holds `identifiers` and `product_id's`, so getting  `product id` became faster.

In general if to compare initial memory value which was on start - about 88 MB, and after all improvements I got 69 MB, and leak per 100 product became 0.5 MB instead of ~8 MB.

What do you think regarding this and memory leaks in Akeneo in general?

(Akeneo 1.5)

Regards, Viktor.

**Comment by a2xchip** [comment]
The third one is really interesting. Was new table created for identifier indexing because identifier itself is in ProductValue table in a line with all other attribute values of a product?

**Comment by NovikovViktor** [comment]
>Was new table created for identifier indexing because identifier itself is in ProductValue table in a line with all other attribute values of a product?

Yes, exactly.

**Comment by ClementGautier** [comment]
Hello @NovikovViktor,

First, thank you for your feedback :)

I was wondering: What is your PHP version during your bench and if you used prod environment and/or if you optimized your composer auto-load during this benchmarks ?

1) Actually I'm not sure that this is required as gc_collect_cycles will be called when the number of objects reach the gc limit. Doing it here could at most free the gc more often but not reduce the leak.

2) This is interesting but I would rather do it in the import/export processes instead of the saver because it could slow down other parts of the application. Basically if you do it in the saver and need these objects after saving, doctrine will fetch them again from the database in order to hydrate new object for your needs.

3) I'm not a big fan of this solution as it will change the model layer in order to bypass a storage issue. Basically in mongodb the fix will not apply. Anyway, **you are right** when you say that fetching the identifier attribute every time from the database is a waste of time and should be avoided. We could simply do a join, as this columns are indexed and save object hydration. If the identifier do not change we could even cache this attribute and save a lot of queries. I would even recommend a persistant cache for that (that we could warmup with the application cache) if it is not possible to change it from the UI.

I'll ask internally at Akeneo about caching on the third point. Be pleased to contribute on this topics by creating pull requests.

**Comment by NovikovViktor** [comment]
Hello @ClementGautier 

>What is your PHP version during your bench and if you used prod environment and/or if you optimized your composer auto-load during this benchmarks ?

I am using 5.6

>1) Actually I'm not sure that this is required as gc_collect_cycles will be called when the number of objects reach the gc limit. Doing it here could at most free the gc more often but not reduce the leak.

Yes, you are right gc clears automatically after it reach limit.

>2) This is interesting but I would rather do it in the import/export processes instead of the saver because it could slow down other parts of the application. 

Actually, yes. But I was testing things with only import process in mind. 

>3) I'm not a big fan of this solution as it will change the model layer in order to bypass a storage issue. Basically in mongodb the fix will not apply. Anyway, you are right when you say that fetching the identifier attribute every time from the database is a waste of time and should be avoided. We could simply do a join, as this columns are indexed and save object hydration. If the identifier do not change we could even cache this attribute and save a lot of queries. I would even recommend a persistant cache for that (that we could warmup with the application cache) if it is not possible to change it from the UI.

Yes, such way could bring a lot of potential troubles to the current database workflow. Way to store sku -> p_id map in Memcache was taken into consideration.

**Comment by NovikovViktor** [comment]
Hello @ClementGautier @a2xchip 
As there is luck of attention, and for me this is not relevant anymore I close this issue.

Best regards, Viktor.
