### ISSUE TITLE
In List filter

### ISSUE THREAD

**Issue by andrelecomte** [akeneo/pim-community-dev#4435]
The In List filter works as expected to display a list of SKUs on the product grid, however, it fails if the SKU contains dashes (eg. 510-00-000-344-0).
The In List filter also behaves differently when trying to filter other attributes besides SKU. When a list is pasted into the SKU filter box the SKUs are recognized as distinct values, however, this fails if a list is pasted into the filter box of any other attribute.

These bugs can be reproduced on http://demo.akeneo.com
![akeneodemo](https://cloud.githubusercontent.com/assets/10606395/15124880/016c4944-15df-11e6-9a10-8d0a3b208946.png)

**Comment by LaureBro** [comment]
Hello @andrelecomte, thanks for your raising this.
For the dash in the sku, we're aware of it - you reported it on the Slack user group, it has been added to our bug tracker. Thanks!
For the In list on attribute "Brand", when you select this filter, with filter "in list" it displays you the brands that are available - Canon, Nikon - if you copy paste values, you need to make sure that it is recognized by the PIM.
For instance, I've created a 3rd brand on demo.akeneo.com: Samsung, when I click "on list", it displays the 3 brands that have been created under the Brand attribute, if I copy paste Samsung, it is displayed like this:
![samsungbrand](https://cloud.githubusercontent.com/assets/13367999/15146522/3aca5e78-16bc-11e6-8dcd-9682a6829d7f.png)
Here on your screenshot, it seems that you're looking for the brand "Canon Nikon" which does not exist, that's why the PIM displays No matches found. Moreover, the brand attribute had not been added to any families in the PIM, so when you filter on it, you do not get any results, except if you did add the brand attribute to at least one family and filled it in.
If I'm mistaken something please do not hesitate to give me more details about it.

Finally thanks to your post, I have noticed a bug when you filter on a brand, once you have added a brand, you cannot remove it unless you remove and then add again the attribute.

Best regards, 

Laure

**Comment by andrelecomte** [comment]
Hi @LaureBro,

The In List filter only recognizes multiple values when filtering SKUs. For instance, the In List filter recognizes "10066052 17404814" as distinct SKUs, however, "Canon Nikon" fails to be recognized as distinct brands.
Please let me know if further explanation or demonstration is needed.

Thank you,

André

**Comment by LaureBro** [comment]
Hello @andrelecomte, 

it does recognize several brands, but they have to be added separately, and appears in grey like below:
![severalbrands](https://cloud.githubusercontent.com/assets/13367999/15153066/1f00b6e4-16d8-11e6-9403-4e046e1b695f.png)
In your screenshot it seems that PIM was looking for "Canon Nikon" not "Canon" and "Nikon", do you see the difference?
But, if I put multiple skus in the SKU/in list, and separate by a comma, they are recognized, whereas they are not in the Brand field. A workaround might be to enter Canon, then press Enter, then Nikon.
Can you try on your side? I've tried on demo.akeneo.com and it's working fine.
I'm checking with my product team why the Brand/in list behaves differently.

Thanks!

Best regards, 

Laure

**Comment by andrelecomte** [comment]
Yes @LaureBro, I see the difference, however, even inputting the values with comma separation fails. The only way the In List filter will work (for attributes other than SKUs) is to input each value one by one, which somewhat defeats the purpose of using a list. I look forward to the product teams response. Thank you!

**Comment by LaureBro** [comment]
Hello @andrelecomte, yes you are right. 
I have informed them, and we'll discuss it before the end of the week, I'll keep you updated!
Best regards!
and thanks again!

**Comment by LaureBro** [comment]
Hello @andrelecomte, 
Here's the feedback from our Product team:

The sku attribute has a specific behaviour because you can actually copy/paste a list in it, we do not have this behaviour for other attribute types, like Brand, Family... so unfortunately it is not considered as a bug.

Best regards, 

Laure

**Comment by LaureBro** [comment]
Hello @andrelecomte, the issue I've noticed following your Github issue on the brand filter will be fixed in the next 1.5 version (when you were filtering on a brand, you could not remove it afterwards). We're planning to release the patch this week.

Best regards, 

Laure

**Comment by LaureBro** [comment]
Hello @andrelecomte, we've released the 1.5.4 version last Wednesday. 
Regarding the original issue, I've created a ticket in our bug tracker (PIM-5767 - Issue with filter "in list" when SKU contains dashes) but we will not be able to duplicate the behaviour of attribute SKU with filter in list for other attribute types.
We'll keep you updated.
Thanks.

**Comment by Hocdoc** [comment]
+1 for pasting texts from Excel for filtering select attributes. 

This is also a *highly* missed feature for our user base who works a lot with Excel together with the PIM. They are using multiple SKU-like fields without spaces.

Pasting a text into a list filter only works for one value, not for multiple values. Unfortunately it is not considered as a bug.

(Just as a reference: nidup has also written some helpful information about filtering in PR #3494 )

**Comment by LaureBro** [comment]
Hello @andrelecomte, @Hocdoc, we've fixed this bug in the 1.5 version :) it will be available in the next patch, we're planning to release it this week.
We'll keep you updated.

Best regards, 

Laure

**Comment by LaureBro** [comment]
Hello, 

The new patch is out (1.5.8), and it contains the fix for this issue.

Regards, 

Laure
