### ISSUE TITLE
I can't delete attribute group - Other

### ISSUE THREAD

**Issue by syrotchukandrew** [akeneo/pim-community-dev#4640]
I've installed Akeneo with minimal data and I have attribute group - Other. I can't delete this attribute group whereas I can delete any my custom attribute group.

**Comment by syrotchukandrew** [comment]
I did it via phpmyadmin, but it will be better to have a button))

**Comment by aRn0D** [comment]
hi syrotchukandrew,

Yes it is impossible because it is the default group, every attributes created without group go into this one. It is used to print them in product edit form (attributs are printed by group). Be careful, if you delete this group and if your attributs don't have group, they will not rendered!
