### ISSUE TITLE
Cannot download uploaded image

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#4687]
In Akeneo 1.5.5 when I upload a picture in the PEF and then click on the download button (the second icon with the arrow in the cloud) it will result in an error 404.

"Only" after saving the product, I can use the download button.

This issue is also reproducible on http://demo.akeneo.com/ .
The problem with a missing thumbnail is already fixed (see #3553, #4476).

**Comment by aRn0D** [comment]
@Hocdoc you right! Thanks for raising that bug. I guess we should hide that icon before saving the product. If you want to submit a PR you are welcome ;)!

**Comment by a2xchip** [comment]
in progress

**Comment by SamirBoulil** [comment]
Hello @a2xchip!

Did you start a PR regarding the hiding of the button ? What can I do to help you fix this issue ?

**Comment by a2xchip** [comment]
@SamirBoulil Thanks for your notice! Yes! I remember i was working on it, not sure why it was not PRed. Will check it on my laptop today and update the status.

**Comment by tamarasaurus** [comment]
Hey @a2xchip, how did your PR go? Did you end up merging it? Let me know and I'll close this ticket.

Thanks,
Tamara

**Comment by a2xchip** [comment]
@tamarasaurus Hello! It ended up by loosing branch when my laptop was stolen last summer :disappointed:

**Comment by damien-carcel** [comment]
Hello @a2xchip .

This issue is nor relevant anymore in 1.7 nor in 2.x. The thumbnail is correctly generated and it is possible to enlarge the image without having save the product yet. If a user try to download the image (which is not possible, as it was not yet really uploaded) he/she will end up with a warning message.

Closing this issue, but feel free to reopen it if you have anymore questions.

Kind regards,
Damien
