### ISSUE TITLE
Call to undefined function in ApcCache.php

### ISSUE THREAD

**Issue by mepdr** [akeneo/pim-community-dev#4829]
**I'm reporting a Bug**

Running *v1.5-latest-icecat* on a fresh ubuntu 16.04 installation with mysql 5.7.12 and php7 + php-apcu 5.1.3 I got

> [Tue Aug 09 15:11:21.247176 2016] [:error] [pid 3535] [client 192.168.30.5:55598] PHP Fatal error:  Uncaught Symfony\\Component\\Debug\\Exception\\FatalThrowableError: Fatal error: Call to undefined function Doctrine\\Common\\Cache\\apc_fetch() in /srv/pim-community-standard/vendor/doctrine/cache/lib/Doctrine/Common/Cache/ApcCache.php:40\nStack trace:\n#0 /srv/pim-community-standard/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(174): Doctrine\\Common\\Cache\\ApcCache->doFetch('DoctrineNamespa...')\n#1 /srv/pim-community-standard/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(147): Doctrine\\Common\\Cache\\CacheProvider->getNamespaceVersion()\n#2 /srv/pim-community-standard/vendor/doctrine/cache/lib/Doctrine/Common/Cache/CacheProvider.php(78): Doctrine\\Common\\Cache\\CacheProvider->getNamespacedId('Pim\\\\Bundle\\\\Cata...')\n#3 /srv/pim-community-standard/vendor/akeneo/pim-community-dev/src/Pim/Bundle/CatalogBundle/Doctrine/ArrayApcCache.php(56): Doctrine\\Common\\Cache\\CacheProvider->fetch('Pim\\\\Bundle\\\\Cata...')\n#4 /srv/pim-community-standard/vendor/doctrine/common/lib/Doctrine/Common/Persist in /srv/pim-community-standard/vendor/doctrine/cache/lib/Doctrine/Common/Cache/ApcCache.php on line 40

Am I missing something?

**Comment by LaureBro** [comment]
Hello @mepdr, 

it looks like you did not follow our technical recommendations: 
MySQL version (SQL)	5.1 ≤ version ≤ 5.6
PHP version 5.4, 5.5, 5.6 

We are working on the compatibility 1.6 and PHP 7.0, but it's not supported yet, only experimental, and Akeneo 1.5 is not compatible with PHP 7.0.
If you're using MySQL 5.7, you need to deactivate the **only_full_group_by** mode to make the PIM works, but this MySQL version is not supported yet.

You can find our full recommendations on the following link:
https://docs.akeneo.com/latest/developer_guide/installation/system_requirements/system_requirements.html

Best regards, 

Laure

**Comment by mepdr** [comment]
Thanks for the answer. I saw the technical recommendations but since php7 is tested on travis, I wrongly thought it could be ok in using php7 which it's the standard and only php version available in ubuntu server 16.04.
Is akeneo 1.6 going to officially support php7 and mysql 5.7 ?

**Comment by LaureBro** [comment]
Hello, no, unfortunately it's not planned for the 1.6.
PHP7 should work with the 1.6, it's being tested (https://docs.akeneo.com/1.5/reference/performances_guide/php7_hhvm.html#php7-and-hhvm-compatibility) but it's not supported yet.
Having Akeneo compatible with MySQL 5.7 is not planned yet.

**Comment by nidup** [comment]
Hi @mepdr !

Thank you a lot for raising this issue.

We fixed it in this pull request https://github.com/akeneo/pim-community-dev/pull/4857 :tada:

You can find extra info about PHP7 support here https://github.com/akeneo/pim-docs/blob/master/reference/performances_guide/php7_hhvm.rst

We're not announcing the official support for now because we don't have yet all continuous integration builds to ensure that 100% of features are working with PHP7, and in the context of our Enterprise Edition, we commit to fix bugs following a Service Level Agreement.

However, I use PHP7 locally since few weeks to develop new features and improvements on upcoming v1.6 and I didn't yet encountered any issues related to PHP7.

Have a good day,
