### ISSUE TITLE
Exception while saving the default channel

### ISSUE THREAD

**Issue by Pacolu** [akeneo/pim-community-dev#4989]
Hello,

I have encountered the following bug. If i edit the sole channel, after the installation (ecommerce) and switch the Locales, for example: I delete "en_US" and add "de_DE" and then save, this error occurs:

> Catchable Fatal Error: Argument 1 passed to Pim\Bundle\UserBundle\Entity\User::setCatalogLocale() must implement interface Pim\Component\Catalog\Model\LocaleInterface, boolean given, called in /var/www/html/akeneo.local/vendor/akeneo/pim-community-dev/src/Pim/Bundle/UserBundle/EventSubscriber/UserPreferencesSubscriber.php on line 220 and defined

after this i cannot see the channels anymore and get this error:

> There are no activated locales
> 500 Internal Server Error - LogicException

But if i first add "de_DE" and click save, and after this delete "en_US" and save, it works without an error. In Addition if i have two channels and switch the locale from "ecommerce" it works too. So I think the problem is something like: I switch the locale, so Akeneo set the channel to "inactive" and before it can set it "Active" again, some sort of validation crashes.

here my system info:
[akeneo-pim-system-info_2016-09-07_10-48.txt](https://github.com/akeneo/pim-community-dev/files/458709/akeneo-pim-system-info_2016-09-07_10-48.txt)

**Comment by elburro1887** [comment]
I have encountered the same issue.

**Comment by nidup** [comment]
Hi @Pacolu and @elburro1887 !

Thank you for raising the issue and for confirm it, i managed to reproduce with a 1.6 install using the minimal installer fixtures set.

This subscriber allows to change the user preference when,
 - a channel is removed
 - a tree is removed 
 - a locale is disabled

Because each user can choose its default "catalog locale", "catalog scope", "catalog tree".

A locale is activated when its associated to a channel, and here, the issue is that we deactivated the last locale by removing it from the channel and in the same time we activate a new locale by adding it to the channel, in this case, the '$activeLocales = $localeRepository->getActivatedLocales();' returns an empty array.

I think that the logic must be a bit re-worked to avoid this case, the added locale should be activated t this point.

Are you interested to investigate and try to fix this issue through a pull request on the 1.6 branch? I'll be happy to help you by reviewing and merging this PR.

If you're interested, I'll need that you read and sign our contributor agreement to merge the pull request https://www.akeneo.com/contributor-license-agreement/

Thank you!

**Comment by a2xchip** [comment]
Will dedicate 6h of free time for this one, but not sure if i will be able to fix it so fast
