### ISSUE TITLE
CSV product import Mongo -> product not caught by akeneo.storage.post_save

### ISSUE THREAD

**Issue by janssensjelle** [akeneo/pim-community-dev#5006]
**I'm reporting a Bug**

I am running Akeneo 1.5.8 with Mongo 2.6 and PHP 5.6.25. 

When I update a product through CSV import, it does not trigger the event listener akeneo.storage.post_save

Configuration of Save Listener:

"  plt_plt_sqs.product_presave_listener:
    class: Plt\PltSqsBundle\EventListener\ProductSaveListener
    arguments:
        - '@service_container'
        - @pim_catalog.saver.product
    tags:
      - { name: kernel.event_listener, event: akeneo.storage.pre_save, method: onPreSave }
"

Without the usage of Mongo, it worked. Is this a bug?

**Comment by nidup** [comment]
Hi @janssensjelle 

Thank you for raising this issue.

We discussed this point with @iulyanp few months ago in following issues and you're right this API is not consistent for any savers in 1.5,
 - https://github.com/akeneo/pim-community-dev/pull/4724
 - https://github.com/akeneo/pim-community-dev/pull/4767

Finally, the following PR have been merged in 1.6 to improve / fix this api (thx @iulyanp !),
 - https://github.com/akeneo/pim-community-dev/pull/4823
 - https://github.com/akeneo/pim-community-dev/pull/4824

We didn't applied this change in 1.5 because it implies several BC Break, so, you can either:
 - take inspiration of these PRs to fix it in your project (overriding the saver)
 - upgrade your project to 1.6

Best regards

**Comment by iulyanp** [comment]
Hi @nidup 

I just want let you know that I upgraded to v1.6 and now we're testing everything. I noticed a small bug on the inner variation type remover. I created also a jira ticket but I get in touch faster with you here. :)
You forgot to remove the if statement from file Pim\Bundle\InnerVariationBundle\StorageUtils\InnerVariationTypeRemover line 89:
```
 $this->objectManager->remove($innerVariationType);
        $this->removeProductVariations($innerVariationType);
        if (true === $options['flush']) {
            $this->objectManager->flush();
        }
```
Also I discovered another bug on the same bundle and I created a gist for it, it is in the jira ticket: MADE-5

Let me know what you think.

Best regards,
Iulian

**Comment by nidup** [comment]
Hi @iulyanp !

Great news for the upgrade!

I don't very well know the InnerVariationBundle, our beloved marketplace team (@fitn and @jmleroux) are in charge to make evolve and to maintain this bundle, they'll get in touch with you :)

Don't hesitate if you see any other issue, it's always a pleasure to discuss and work with you :)

Best regards,
