### ISSUE TITLE
[question] Group on datagrid / filter

### ISSUE THREAD

**Issue by julienanquetil** [akeneo/pim-community-dev#5051]
**I'm asking a Question**
Did anyone have an idea why on datagrid you can't sort by Group (variant group) ? 
And why the "group" filter is "in" only and not like family one "in / empty" ?

In my case it's a "needed" thing, but perhaps i'm the only one.. 
Before starting working on it, I prefer ask the team.

Thanks

**Comment by fabienlem** [comment]
Hi @julienanquetil !

It's not possible to sort the product grid by group because a product can belong to several groups. We assume sorting multi-valued data doesn't really make sense.

Concerning your second question, the empty filter isn't available on the group filter just because we thought it was not needed. If you are you interested to contribute this improvement through a pull request on the **master** branch, I'll be happy to help you by reviewing and merging this PR.

Regards

**Comment by Doodoune** [comment]
Hi! 

I close this issue. Feel free to re-open it if you're interested to contribute this improvement.

Regards,
