### ISSUE TITLE
Price import: Missing currency values are not ignored

### ISSUE THREAD

**Issue by Hocdoc** [akeneo/pim-community-dev#5059]
**I'm reporting a Bug**

Bug in Akeneo 1.5.8 + Akeneo 1.6:

When importing products with a missingcurrency columnm, the old currency value will get removed instead of ignored.

Steps to reproduce on http://demo.akeneo.com/:

1. Check the price of the product with the SKU `OROMUG_BO`: EUR 5 and USD 5.
2. Import the following file with the `csv_product_import`:

    sku;price-EUR
    OROMUG_BO;7

3. After the import the product has the price: EUR 7 and USD is blank. 

Our users expect that USD is still 5 instead of blank, because the currency wasn't mentioned in the imported CSV file.

**Comment by ahocquard** [comment]
Hello @Hocdoc  
and thanks for reporting this issue.

This bug is due to the behaviour of the function : 
\Pim\Component\Catalog\Updater\Setter\PriceCollectionAttributeSetter::setPrices

Before setting prices, this function deletes every currency values, even if the currency is not specified in the "data" parameter.
We will not patch this issue in the 1.6 minor version for the moment, because it is not backward compatible (in term of behaviour). 

You can remove the else block in those lines of code  (in the function setPrices) : 

```
        if (null === $value) {
            $value = $this->productBuilder->addProductValue($product, $attribute, $locale, $scope);
        } else {
            $prices = $value->getPrices();
            foreach ($prices as $price) {
                $price->setData(null);
            }
        }
```

Please do note it changes the behaviour of setAttributeData (which call "setPrices" function) : 
- before removing these lines of code, passing an empty array for the data parameter deleted every currency values for a price
- after removing these lines of code, passing an empty array for the data parameter do nothing

CI  do not report any behaviour problem int the PIM with those changes.

Best regards,
Alexandre

**Comment by Hocdoc** [comment]
Thank you very much, this worked as expected.

I hope the change will be in 1.7 in the Akeneo code base ;-).

**Comment by Djamy** [comment]
Hi,

It seems that we have this same bug on the demo.akeneo.com with the version 2.2.2.

**Comment by simoncarre** [comment]
Same issue here with 2.3.4 version.
