### ISSUE TITLE
More significant error message if catalog has no identifier

### ISSUE THREAD

**Issue by mariobeiser** [akeneo/pim-community-dev#5079]
**Throw a more significant error message when the catalog has no attribute selected as identifier**

This can happen, when products and attributes are e.g. manipulated via database.

**Error message currently**
`Exception trace:
 () at /var/www/pim/vendor/doctrine/collections/lib/Doctrine/Common/Collections/ArrayCollection.php:48
 Doctrine\Common\Collections\ArrayCollection->__construct() at /var/www/pim/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:555
 Doctrine\ORM\UnitOfWork->computeChangeSet() at /var/www/pim/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php:404`

**Comment by grena** [comment]
Hello @mariobeiser ,

Values are vertically stored in the table because we use EAV pattern, so we can't apply uniqueness constraint on the table. If you manipulate data through DB, we can't ensure data consistency neither and therefore handle this case.

I close this issue for the reason explained above.

Thank your for your understanding and feel free to answer if you had this error in another way than by updating directly the DB :)

**Comment by mariobeiser** [comment]
Hello Adrien,

I can't manage it to reproduce without DB. 

I solved this by debugging the ArrayCollection while importing new data through an import-job. Before that, I had cleared all attributes via DB.

So perhaps it is a dev-related issue. But perhaps, the way I did it, is really common while developing.

Whatever. If you have no further idea of reproducing, I fully agree of you close this.

Kind Regards
Mario
