### ISSUE TITLE
Variant items disapear if there is more than 200 sku in a group

### ISSUE THREAD

**Issue by julienanquetil** [akeneo/pim-community-dev#5087]
**I'm reporting a Bug**

I'm on 1.6.3 and we got some "big" variant group like with more than 200 sku (with 3 axis)
Because there is too much item the url is very massive and I got a 414 Request-URI Too Long error.

I try several things on apache level without succes.

As @juliensnz  said on Slack, it not easily fixable... but In my case the update can only be made by upload now ;)
Thanks

**Comment by fabienlem** [comment]
Hello @julienanquetil,

I well reproduced this bug on our demo. Thank you for reporting it !

Similar issue has been fixed on the attribute list screen of the PIM. The goal is to use POST parameters instead of GET ones. Here is the link to the related PR : https://github.com/akeneo/pim-community-dev/pull/3876

Are you interested to contribute a fix through a pull request on the **master** branch ? (The master branch will be our upcoming 1.7).  I'll be happy to help you by reviewing and merging this PR.

Thank you.

**Comment by julienanquetil** [comment]
Thanks, unfortunatly i'm on a ecommerce website launch (with 5 more in the next month) and didn't have too much time to "fix it" yet...
But if nobody do it, i will try to take a look end of this year.

**Comment by fabienlem** [comment]
Hello @julienanquetil,

Ok, no problem! It's in the project (https://github.com/akeneo/pim-community-dev/projects/1#card-413685) so somebody else can take a look at this issue. 

I will keep you updated if we release a patch.

Kind regards

**Comment by julienanquetil** [comment]
Hi this one is already fix since 1.6.16 on my side. i think you can close it.
Thanks
