### ISSUE TITLE
[v1.6.3] Boolean fields part of the completeness not working if are not set at least once with "true"

### ISSUE THREAD

**Issue by iulyanp** [akeneo/pim-community-dev#5101]
**I'm reporting a Bug**

Hello @nidup,

We just noticed that for the fields of type boolean that are included in completeness on a family, you are not able to set the product as complete if you don't check at least once the boolean field on yes. 
This is reproducible on your demo server and also on EE.

Best regards,

**Comment by fabienlem** [comment]
Hello @iulyanp

Thank you for reporting this. We are aware of this behavior, and even if the problem seems not complicated, there are several approaches to fix it, programmatically speaking. We are planning to improve the boolean attribute in the next version of the PIM.

For now, the best solution is just to not include boolean attributes in the completeness calculation. To better understand your needs, can you be more specific about your use case?

Kind regards

**Comment by iulyanp** [comment]
Hello @fabienlem,

Thank you for your feedback but we can't exclude them from completeness. 
There are other services that will consume the "events" we send from PIM to Eventstore. 
They will expect those fields to be set in the events because are required for them.
When can we expect a fix for this?

Best regards,

**Comment by fabienlem** [comment]
Hello @iulyanp,

Unfortunately, we will not fix it. This behaviour cannot be changed in a patch, because it will imply to force a value which will be a product evolution and could impact other users, our Product team is working on a new boolean type, but I cannot tell you yet in which version this will be available. I have added a note regarding your request in their suggestions of improvement queue.

Another option may be to use a simple select attribute instead of the Yes/No attribute. In this case, it will be mandatory for users to select a value. The completeness will work as excepted.

Regards

**Comment by fabienlem** [comment]
I'm closing this issue, feel free to reopen it if you want further information.
