### ISSUE TITLE
Few improvements on commands (install / batch imports)

### ISSUE THREAD

**Issue by iulyanp** [akeneo/pim-community-dev#5209]
**I'm reporting a Bug**

Hello,

We are close to migrate all data from Magento to PIM and while running the command:
`app/console pim:install` we noticed that every time a Warning or an Error is catch in the fixture import the install is failing. 
Wouldn't be a good idea to stop the install only on Error and on Warning just to skip that item? 
I investigated and on the CommandExecutor and the if statement form here is the issue.
https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/InstallerBundle/CommandExecutor.php#L62
Solution:
```
if (BatchCommand::EXIT_ERROR_CODE == $exitCode {
 // .....
}
```

Another small thing that I think it would be useful on the install process is a better output on what the command is processing, because right now you'll get only what was already processed and it's frustrating that you can't see what the script is doing (on what step is spending more time for example).
I think we could add `$output->writeln(sprintf('<info>Processing %s ...</info>', $jobInstance->getCode()));` to line 164 and we will have a really nice feedback with what job is running.
https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Bundle/InstallerBundle/Command/DatabaseCommand.php#L163

Also a better output or log of the warnings on batch import would be very nice.
In https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Bundle/BatchBundle/Command/BatchCommand.php#L170
we could log the warnings or even write them as output:
```
$nbWarnings = 0;
/** @var StepExecution $stepExecution */
foreach ($jobExecution->getStepExecutions() as $stepExecution) {
$nbWarnings += count($stepExecution->getWarnings());
/** @var Warning $w */
      foreach ($stepExecution->getWarnings() as $w) {
            $output->writeln($w->getReason());
      }
}
```

Please let me know what you think.

Best regards

**Comment by fabienlem** [comment]
Hello @iulyanp!

Interesting suggestions! I discussed of them with the team. 

We think the warning messages should stop the installation because data used as fixtures must be good, as they are the basis of the project. It's better for user to take time to fix the fixtures instead of skip them.

Your other improvement suggestions are welcome! The running jobs feedback could be enabled if the user launch the install process with the "-v" flag. It would be great if you could contribute through a pull request on the **master** branch.

Don't hesitate to ping us if you need further information or any assistance. As usual, we will help you to review your pull request.

Thank you!
Fabien

**Comment by iulyanp** [comment]
Hello @fabienlem ,

Thank you for your feedback.
I don't really understand why a warning message should stop me from installing the application. IMHO a warning should be just a warning.

As for the other things I will try to create a PR in the next few days.

Best regards
