### ISSUE TITLE
Attribute list filters

### ISSUE THREAD

**Issue by a2xchip** [akeneo/pim-community-dev#5230]
**I'm reporting a Bug**

For version >= 1.6

On attribute list page when using filtering by **Type** or **Group** filters **All** acts same way other filters do. 

Scenario:

I'm on attributes listing page
And I press **Type** filter and select Yes/No
Then I should see only **Yes/No** attribute types

Would fail because **All** is not deselected automatically.

**Comment by fabienlem** [comment]
Hello @a2xchip,

This is the normal behavior. It works the same way on other similar filters and grids. However, we aware we could improve the user experience by changing this behavior, that's why an improvement suggestion is already logged on our side. We will consider it for upcoming versions of the PIM.

Thank you for your message, we will keep you updated!

Regards,
Fabien

**Comment by fabienlem** [comment]
Hello @a2xchip,

I'm closing this issue, feel free to reopen it if you need further information.

Regards,
Fabien

**Comment by a2xchip** [comment]
Hello @fabienlem ! it was just report. No problem if it is already on tracker.
