### ISSUE TITLE
[Security] escapeshellcmd and escapeshellarg are not safe

### ISSUE THREAD

**Issue by aistis-** [akeneo/pim-community-dev#5857]
PIM uses escapeshellcmd and escapeshellarg in some places to sanitize console commands.

These functions are not consider as safe: https://gist.github.com/Zenexer/40d02da5e07f151adeaeeaa11af9ab36

Usages:

- https://github.com/akeneo/pim-community-dev/blob/b69510874fe3d7f66a4fc859c70d4cbe2ca4aceb/src/Akeneo/Component/Console/CommandLauncher.php
- https://github.com/akeneo/pim-community-dev/blob/837c81fd0a0496a37a99f7cea3a24439f50efa9f/src/Akeneo/Bundle/BatchBundle/Launcher/SimpleJobLauncher.php

BTW, why PIM does not use https://github.com/symfony/process ?

**Comment by momoss** [comment]
Hello @aistis- , 

First, thank's for your feedback,
In a past time, we try to use the Symfony process class but we had some memory leak issues due to our large process.

Recently we have enforced our tests on using escapeshellcmd and escapeshellarg in SimpleJobLauncher [#5288](https://github.com/akeneo/pim-community-dev/pull/5288/files).

But if you want to implement the use of this class in the CommandLauncher and SimpleJobLauncher, you can contribute and make a pull request, I give you the following link of our [contribution guide](https://docs.akeneo.com/1.7/contributing/contribution_guide.html) , 

Best regards,

Philippe.
