### ISSUE TITLE
Error when deleting export profile

### ISSUE THREAD

**Issue by gotgelf** [akeneo/pim-community-dev#5949]
Hello 👋 ,

We're using Akeneo CE 1.7

Currently if you go to export profiles, select any and try to delete it (from edit profile page)you will get next error (browser console):

<img width="337" alt="screen shot 2017-03-19 at 00 12 03" src="https://cloud.githubusercontent.com/assets/4104908/24076738/b6693744-0c38-11e7-9f04-da9984c96c42.png">

**Comment by juliensnz** [comment]
Hello @gotgelf,

Thanks a lot for this bug report, you spotted a good one :)
The problem is that the Job instance remover uses `identifier` key instead of `code` (https://github.com/akeneo/pim-community-dev/blob/1.7/src/Pim/Bundle/EnrichBundle/Resources/public/js/remover/job-instance-import-remover.js#L26 and https://github.com/akeneo/pim-community-dev/blob/1.7/src/Pim/Bundle/EnrichBundle/Resources/public/js/remover/job-instance-export-remover.js#L26).

Would you be interested to contribute and handle the fix yourself? If yes, you can create a pull request from your fork, change those two remover to use code instead of identifier as a key and add a small behat scenario to ensure that the issue will not come back in six months :)

**Comment by gotgelf** [comment]
Hello @juliensnz will make pull request this week.

**Comment by gotgelf** [comment]
Hi @juliensnz, can you please give me reference for the ticket (PIM-xxxx), to create the patch?

**Comment by juliensnz** [comment]
Hello @gotgelf,

Awesome! You can name your branch like that: GITHUB-5949 :)

**Comment by SamirBoulil** [comment]
Hello @gotgelf !

Thanks for raising this issue, the PR fixing the bug has been merged today 🎉  !
