### ISSUE TITLE
 Initialization without removing database

### ISSUE THREAD

**Issue by ClementDy** [akeneo/pim-community-dev#6263]
**I'm asking a Question**

Hi,

It's maybe trivial, but, is there an easy way to configure the initialization to not delete the database if it exists ?

In my example, i've got a container with mysql and another with akeneo. I would like, when i kill and restart my Akeneo container, that it doesn't drop the database during the new initialization and reuses existing data.

Regards

**Comment by damien-carcel** [comment]
Hello Clément.

That depends on how you manage your containers. As you have 2 separate containers, I imaging you are with Docker, and not LXC?
I think the easiest way would be that recreating the Akeneo container does not destroy data. As you can keep alive (or just stop and restart) your MySQL container, you can keep your database content.

So I guess your problem is on the Akeneo container itself. Is your Akeneo application inside the container, or outside and linked through a volume?

In the first case, destroying your container would indeed make you lose the date generated during the install process (like some product images, for instance). Personally, I would place the files I want to keep in another volume, so they are not lost. All you would have to do when restarting the container, then, would be to re-install the assets (’app/console -e=prod pim:installer:assets’).

In the second case, if your Akeneo application is already outside the container, then destroying the Akeneo container will not result in data loss, only in restarting your server. This is what I do when I develop in Akeneo.

I hope this helps you, don’t hesitate if you have more questions.

Regards,
Damien

**Comment by ClementDy** [comment]
Yes, i'm using docker. 

In my example, my SQL container use a Volume but not the Akeneo container. 

Maybe that i say is confused, but my steps are : 
1. Instanciate MSQL container
2. Instanciate Akeneo container (Configured to save data on the previous database)
3. Play with Akeneo (Saving data on MySQL container)
4. Delete Akeneo container. 
5. Instanciate another Akeneo container (Configured to use the previous database)

So, during the last instanciation, i can see that in the logs : 

```
Prepare database schema (driver: doctrine/orm)
Dropped database for connection named `test`
Created database for connection named `test`
```

And, this initialization remove my data. I suppose that the processus is to "drop and create" the database, but, the processus i want is to "update or create".

Thanks for your reactivity and your answer.

Regards

**Comment by damien-carcel** [comment]
Hello again.

OK, if you have this message in your logs, that means one of those commands: `pim:install` or `pim:installer:db` (the first one include the second, plus some other commands) is called during the container initialization.
You need to find where it is done, then remove this call to this command, but execute it by hand, only when you need it (during first instanciation).

What docker images do you use? I could take a look at it too.

Regards (and good evening 😉),
Damien.

**Comment by ClementDy** [comment]
Hello, 

Yes, `pim:install` is used during the initilization. (In the file : entry/akeneo-initialize.sh)
I'm using this project : [https://github.com/pardahlman/docker-akeneo/tree/master/akeneo](https://github.com/pardahlman/docker-akeneo/tree/master/akeneo)

So, i replace this command : `php app/console pim:install --env=prod` by this : `php app/console -e=prod pim:installer:assets` and that's worked i recovered my data. Just some troubles, now i can't add products, I do not see anymore for exemple, my families, products or attributes, in the corresponding overview (but i can see in the System information that i have few products, families..) and few files was not generated like "file_storage" in the /akeneo/app.

Thanks for your help. 

Have a nice day!

Regards

**Comment by damien-carcel** [comment]
Hello @ClementDy .

Nice it works better. Indeed, the fact `file_storage` is missing is normal, as the PIM is downloaded by the Dockerfile, it is destroyed at each reboot. And as it contains the product medias, it can be problematic ;-).

If you really want to be able to easily reboot your container without trouble, my advice would be to not have the PIM inside it. You can take a look at my [Dockerfiles](https://github.com/damien-carcel/Dockerfiles) to have some insight. Basically, I download the PIM myself (from GitHub, or the website, whatever) and link it through volume to my container. This way, I can restart the container as much as I want, my PIM data will remain untouched.

Another way, if you really want to have the PIM inside the container, would be to share only what you need to keep in volumes from your container, and ensure it is kept between reboots.

Regards,
Damien

**Comment by ClementDy** [comment]
Hello,

Thanks for these informations, i'm going to explore this. 

Regards

**Comment by damien-carcel** [comment]
Hello.

If it's OK with you, I'm closing the issue. Don't hesitate to reopen it if you have any more questions or comments.

Regards,
Damien.
