### ISSUE TITLE
Akeneo Performance Issues

### ISSUE THREAD

**Issue by prabhassharma** [akeneo/pim-community-dev#6444]
Hi,

We are using Akeneo CE 1.7.5 and facing some major performance issues. Below is the list of issues:

1. All import and export jobs start with the generic error message "An issue occurred in import/export", however in the backend they continue to run.
2. We have 7-8 users accessing the system. When only 2 users are logged in the system works fine - no errors, however as the number of users increases the performance goes down gradually.

To give an idea of the data in Akeneo state for us:
1. We have about 92K products.
2. 20k variants
3. 160+ category and subcategory combinations.
4. PHP version - 5.6.30
5. MySQL Verison - 5.0.11

In order to troubleshoot we migrated the Akeneo DB to a separate server but to no avail.
Any help is much appreciated.

Thanks,
Prabhas

**Comment by LaureBro** [comment]
Hi @prabhassharma, 

For imports and exports, do they continue to run until they are completed? 
Since when do you have this issue? Is it happening on all import/export profiles?
Regarding the global performances, 7 or 8 simultaneous users should not impact performances, what is your server configuration? 
If you have many localisable and/or scopable attributes, locales and channels, it can impact the PIM. We advise to use MongoDB if the number of product values is higher than 5M, the following link explains how to calculate the number of product values: https://docs.akeneo.com/1.7/reference/scalability_guide/more_than_5M_product_values.html
Here is our scalability guide: https://docs.akeneo.com/1.7/reference/scalability_guide/

Finally, what you can do is check where the slownesses come from:
You can try to: 

- Use the Symfony’s profiler timeline tab to identify what part of the execution takes most of the time.
- Use blackfire.io in order to profile the requests which take too much time.
- Use MySQL built in “SHOW PROCESSLIST” query to identify queries which take too long to run (See: MySQL documentation: [SHOW PROCESSLIST Syntax](https://dev.mysql.com/doc/refman/5.6/en/show-processlist.html)).
- Use MEMINFO to analyse memory leak issues (See: [MEMINFO GitHub repository](https://github.com/BitOne/php-meminfo/)).

By the way, I see that your MySQL version is not part of the MySQL versions supported (5.1 ≤ version ≤ 5.6) (see https://docs.akeneo.com/1.7/developer_guide/installation/system_requirements/system_requirements.html) 

Please let me know if the above information helped you, 

Kind regards 
Laure

**Comment by prabhassharma** [comment]
@LaureBro Thanks a lot for your response. We are infact using MySQL 5.6, however the product calculation was the real issue here.

I was just counting the number of SKUs. Based on the that formula we more than 5M products.
We shifted to hybrid storage which seems to have fixed the issues.

**Comment by LaureBro** [comment]
Hello @prabhassharma, thanks for your feedback! 
Happy to know that the performances issues are now gone :)

Kind regards,

**Comment by prabhassharma** [comment]
Hi @LaureBro,
As per your suggestion we did the migration using the steps listed here [https://docs.akeneo.com/1.6/developer_guide/installation/setup_hybrid_storage_mysql_mongo.html]. All steps were executed successfully.

After the changes, as I mentioned the system seemed OK. However, at the database level we are not seeing any data in the Mongo DB. MySQL DB (which was already in use) does show the data.

Is there another way to switch to Hybrid SQL if we already have data in MySQL and also how do we migrate this data.

Thanks,
Prabhas
