### ISSUE TITLE
Bug: Running multiple Batch from type "csv_product_export" in the same meta command leads to concatenated output 

### ISSUE THREAD

**Issue by wucherpfennig** [akeneo/pim-community-dev#6590]
If I run multiple batch jobs (csv_product_export) after another in my custom bundle like (simplified):

```
$jobDefinition['command'] = 'akeneo:batch:job';
$command = $this->getApplication()->find($jobDefinition['command']);
$input = new ArrayInput($arguments);
return $command->run($input, new NullOutput());
```
The output file contain the output from the previous export run eg:

Job A: Output A
Job B: Output B
Job Meta: Run Job A first, Do something, Run Job B third

Run separately
Output: everything ok ( File A, File B)
Run in sequenz (Job Meta):
Output:  concatenaded (File A ok, File B contains content from A)

Am I doing something wrong or are there some caches which need be cleared previous to run a similar export again?

**Comment by ahocquard** [comment]
Hello,

In fact, you have discovered a bug that I had when adding integration tests on our exports:
https://github.com/akeneo/pim-community-dev/blob/master/tests/JobLauncher.php#L108

What happens is that we first write into a buffered file the data, and at the end, we put the content of this file into the exported file.

But when we copy the buffered data into the exported file, the buffer is not flushed or deleted at the end. So, when you are doing a second export, you have the data of your previous buffer inside.

Buffer used (you can see this buffer is use destruct method to delete the buffered file): 
https://github.com/akeneo/pim-community-dev/blob/master/src/Akeneo/Component/Buffer/JSONFileBuffer.php
extended by:
https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Component/Connector/Writer/File/FlatItemBuffer.php

And you can see that the flush method does not reset the buffer:
https://github.com/akeneo/pim-community-dev/blob/master/src/Pim/Component/Connector/Writer/File/Csv/Writer.php#L107

I've tried to apply a fix but it would need more works, because there is another bug with the configuration that is kept from the previous export execution as well, leading to another bug.

The (quick) fix was to unset the buffer and recreate it in the flush method of the writer.
But I don't like this solution because using destruct to delete the buffer is not OOP.

Regards,
Alexandre

**Comment by wucherpfennig** [comment]
@ahocquard thank you for the feedback...

Might it be that this issue is somehow connected to not deleted `akeneo_buffer_XYZ` files in `/tmp`?

**Comment by ahocquard** [comment]
@wucherpfennig I think so, the file is just deleted at the end of the process execution.

**Comment by aRn0D** [comment]
hi @wucherpfennig 

Could you give you the info.txt file to know which version is impacted?

Thank you.

**Comment by ahocquard** [comment]
@aRn0D It seems the same problem in this ticket https://github.com/akeneo/pim-community-dev/issues/3998 (I suppose it's 1.4 regarding the date).

**Comment by wucherpfennig** [comment]
@aRn0D @ahocquard 

did not find any info.txt ;-) we are running on CE 1.7.6

**Comment by wucherpfennig** [comment]
This bug is still open as of 1.7.12

**Comment by wucherpfennig** [comment]
I am not sure if we are doing something wrong or whether it is actually a bug as mentioned by @ahocquard 

**what works:** `akeneo:batch:job jobname`
run multiple jobs after each other or simultaneously via crontab results in nice output files

**what does not work:** `custombundle:metajob`
run a "meta" command from a custom bundle which basically is just a wrapper bundle to easily call multiple jobs after each other like.

        // run akeneo export command
        $command = $this->getApplication()->find('akeneo:batch:job');
        $arguments = array(
            'command' => 'akeneo:batch:job',
            'code' => $akeneoExportJob,
            '-c' => json_encode(array(
                'filePath' => $pathToExportFile
            )),
            '--no-log' => TRUE,
        );

        $input = new ArrayInput($arguments);
        $returnCode = $command->run($input, new NullOutput());

 this approach results in concatenating all previous jobs to the current one... so the first output file is ok. the second one contains the output from the first one and the current one. the third one contains contents from second and third one and so on...

We are currently running on 1.7.12

If anybody has a solution for this issue please do not hesitate to let us know...

best regards

wucherpfennig

**Comment by ahocquard** [comment]
As said in this ticket https://github.com/akeneo/pim-community-dev/issues/3998, you can execute each job in a dedicated process to avoid this kind of isolation problem.

**Comment by Doodoune** [comment]
Hi! I close this issue. Feel free to reopen it, if you still have this problem.
Regards,
