### ISSUE TITLE
MongoDB Indexes not being created when using ElasticSearch Bundle

### ISSUE THREAD

**Issue by nei** [akeneo/pim-community-dev#6979]
**I'm reporting a Bug??**

When I run ```php app/console pim:product:ensure-mongodb-indexes --env=dev -vvv``` Pim is not creating the indexes properly.

My Collection has currently 13 indexes, when it gets to ensureAttributesIndexes it does not generate the indexes for attributes..

Since I have only 13 indexes, I would expect it to create (64-13) another 51 indexes and not ignore all.

```
db.pim_catalog_product.stats();
{
        "sharded" : false,
        "ns" : "dt_akeneo.pim_catalog_product",
        "count" : 407069,
        "size" : 11068131200,
        "avgObjSize" : 27189,
        "storageSize" : 17678134816,
        "numExtents" : 48,
        "nindexes" : 13,
        "lastExtentSize" : 536600560,
        "paddingFactor" : 1,
        "systemFlags" : 0,
        "userFlags" : 1,
        "totalIndexSize" : 208185488,
        "indexSizes" : {
                "_id_" : 14896672,
                "family_1" : 18085312,
                "categoryIds_1" : 22058848,
                "groupIds_1" : 17725568,
                "normalizedData_enabled_1" : 8960896,
                "normalizedData_created_1" : 18175248,
                "normalizedData_updated_1" : 18175248,
                "normalizedData_sku_1" : 21372064,
                "normalizedData_completenesses_channel1-en_GB_1" : 17439408,
                "normalizedData_completenesses_ebay1-en_GB_1" : 12811792,
                "normalizedData_completenesses_ebay2-en_GB_1" : 12811792,
                "normalizedData_completenesses_channel3-en_GB_1" : 12844496,
                "normalizedData_completenesses_channel4-en_GB_1" : 12828144
        },
```

It is PIM 1.7 with ElasticSearch.

**Comment by nei** [comment]
I've managed to fix this using this code:

```
protected function ensureIndexes(array $fields, $indexType = self::ASCENDANT_INDEX_TYPE)
    {
        $collection = $this->getCollection();
        $preNbIndexes = count($collection->getIndexInfo());

        $indexOptions = [
            'background' => true,
            'w'          => 0
        ];

        $slots = (self::MONGODB_INDEXES_LIMIT - $preNbIndexes);
        foreach ($fields as $field) {
            try {
                $this->logger->info(sprintf('Creating index for field (%s)', $field));

                if ($slots === 0) {
                    $this->logger->error(sprintf('Too many MongoDB indexes, skipping (%s)', $field));
                    break;
                }

                $collection->ensureIndex(
                    [$field => $indexType],
                    $indexOptions
                );
            } catch (Exception $e) {
                $this->logger->error($e->getMessage());
            }

            $slots--;
        }
    }
```

**Comment by nei** [comment]
I ended up realizing that Pim\Bundle\ElasticSearchBundle\Doctrine\MongoDBODM\IndexCreator is being called and there all my attributes are being ignored.

I know it will be use Elasticsearch on grids but should elasticsearch block mongo of being indexed
 properly? I believe even with Elasticsearch we still do queries on MongoDB.

**Comment by BitOne** [comment]
Hello @nei,

This is by design and a desirable feature: if you have big catalog, which must be definitely the case if you are using the ElasticsearchBundle, having a lot of MongoDB indexes can make it slow.

Indeed, if all the MongoDB indexes cannot fit into memory, no MongoDB index (even the _id !) will go in the memory, and all query to MongoDB to get a specific document by its _id will be very slow.

See https://docs.mongodb.com/manual/tutorial/ensure-indexes-fit-ram/

Another reason to reduce the index in MongoDB, is that we have two kind of indexes:
 - system indexes, like _id, completenesses, categories, which are critical because used a lot in the application
 - value indexes, which are indexes for attributes that are defined as useable in the grid

The problem is that these 2 indexes type will compete for the maximum 64 index slots available. So if you don't remove the value indexes, they can take the place of some system indexes and make the application very slow.

So as the ESB is used by the grid, there's no need anymore to have value indexes inside MongoDB, as they are now inside Elasticsearch.

In your case, if you need to do some query based on attribute value in your custom code, you should use the ProductQueryBuilder provided by ElasticsearchBundle.

By commenting the method in the ESB as you did, you are breaking the application.

And of course we strongly recommend against breaking the application ;)

**Comment by nei** [comment]
Hi @BitOne 

Thank you for your update. I've done this just for tests purpose :) I was curious because I had just the system indexes and just 1 value indexed for the unique attribute. all the others were being ignored.

I remember facing the maximum of 64 indices in the past (before we setup ES) so I was scary it was not indexing properly now since we had just a couple. Thanks for confirming that is the desired behavior! appreciate that.
