### ISSUE TITLE
In TreeListener.php line 72: Tree object class: Pim\Bundle\CatalogBundle\Entity\Category must have tree metadata at this point 

### ISSUE THREAD

**Issue by kamranmalikawan** [akeneo/pim-community-dev#7509]
**I'm reporting a Bug**

Please update to the last available patch for the version 2.1 I am adding a new property in category and facing this issue.

In TreeListener.php line 72: Tree object class: Pim\Bundle\CatalogBundle\Entity\Category must have tree metadata at this point

**Comment by EricPaulson** [comment]
Did you get an answer (or resolution) to this? I have the same issue.

**Comment by jpinzontopgroup** [comment]
Be sure your are loading parent.

In file  /src/Acme/Bundle/CatalogBundle/AcmeCatalogBundle add

    public function getParent()
    {
        return 'PimCatalogBundle';
    }

**Comment by smkerz** [comment]
Hi, I get the same issue. I tried jpinzontopgroup fix. But it did not work, I stll have the original error :

In TreeListener.php line 72: Tree object class: Pim\Bundle\CatalogBundle\Entity\Category must have tree metadata at this point

**Comment by Doodoune** [comment]
Hi!

Your category class extends `Pim\Bundle\CatalogBundle\Entity\Category`? Can you send us your code?

Regards,

**Comment by smkerz** [comment]
Hello!

I did exactly the instructions from this : https://docs.akeneo.com/2.3/manipulate_pim_data/category/add_new_properties_to_a_category.html

Regards,

**Comment by karthik32cse** [comment]
Solution:
-----------
The above issue is occured due to the DependencyInjection. In order to fix this issue follow the below instructions,

Creating an Extension Class:
----------------------------------------
1. It has to live in the DependencyInjection namespace of the bundle;
2. It has to implement the ExtensionInterface, which is usually achieved by extending the Extension class;
3. The name is equal to the bundle name with the Bundle suffix replaced by Extension (e.g. the Extension class of the AcmeBundle would be called AcmeExtension and the one for AcmeCatalogBundle would be called AcmeCatalogExtension).

Code:
-------
**# /src/Acme/Bundle/CatalogBundle/DependencyInjection/AcmeCatalogExtension.php**	
`<?php

namespace Acme\Bundle\CatalogBundle\DependencyInjection;

use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Loader;
use Symfony\Component\HttpKernel\DependencyInjection\Extension;

class AcmeCatalogExtension extends Extension
{
    public function load(array $configs, ContainerBuilder $container)
    {
        $loader = new Loader\YamlFileLoader($container, new FileLocator(__DIR__.'/../Resources/config'));
        $loader->load('entities.yml');
    }
}`

_Let me know if you have any questions_ 

Regards,
Karthik Dhakshinamoorthy

**Comment by solivier** [comment]
hi @kamranmalikawan 

As @karthik32cse said you should be sure the dependency injection configuration is perfectly loaded. And the name should always follow the bundle name. As symfony documentation says:

> The name is equal to the bundle name with the Bundle suffix replaced by Extension (e.g. the Extension class of the AppBundle would be called AppExtension and the one for AcmeHelloBundle would be called AcmeHelloExtension).

cf https://symfony.com/doc/3.4/bundles/extension.html

Cheers
