### ISSUE TITLE
2.1.4 : Completeness, associations and comments are not available for product models

### ISSUE THREAD

**Issue by kanduvisla** [akeneo/pim-community-dev#7632]
I'm using product models and I noticed that the following options (that are available for products) are not available for product models:

- Completeness
- Associations
- Comments

Is there a specific reason why these are not available? It seems to me that if you have common properties for a product you also can have common associations and comments. For example: if I have a product with 100 variants that has associations to other products, I now have to manually set them for each variation, or export and import the data.

**Comment by laouache** [comment]
+1 
Agree

**Comment by Delphineray** [comment]
Hello,

Thank you for your feedback.

There is no completeness on product models, there are not real products, there are used to manage the common properties of their children variant products, but we have 2 indicators:
- the missing required attributes on the product models for the completeness of its children products (with a filter in the product model form on the missing required attributes)
- the number of children variant products complete out of the number of variant products for a product model 

![product_model_diana_red___edit](https://user-images.githubusercontent.com/10232850/36217217-26421fa8-11b1-11e8-8fda-ae208790c65d.png)

About associations, since 2.1, we can associate a product to a product model but we cannot directly associate a product model (only its children products, easier with the mass associations in 2.1: you can mass associate a product model and all its children products will be associated) but it's feature we plan to do.
About comments, it’s not prioritized yet.

Regards,
Delphine

**Comment by damien-carcel** [comment]
I'm closing this issue as it is answered.
Don't hesitate to open it again if you are not satisfied by the answer, and don't hesitate to open other issues if you have other questions.

Kind regards,
Damien.
