### ISSUE TITLE
2.1 httpd container won't run following docker-compose setup

### ISSUE THREAD

**Issue by lferrao** [akeneo/pim-community-dev#7692]
Following a fresh install of version 2.1 of the pim-community-dev, everything seems to work normally except the httpd exists with error 1 immediately as seen in the following screenshot:

![image](https://user-images.githubusercontent.com/6348118/36428877-5d72e698-1651-11e8-97d4-17f528600b80.png)

Steps to replicate:

1. tar xzf v2.1.1.tar.gz
2. cd pim-community-standard-2.1.1
3. cp docker-compose.yml.dist docker-compose.yml
4. docker-compose up -d (with or without docker-compose pull)

**Comment by damien-carcel** [comment]
Hi @lferrao .

This problem comes from a conflict between the latest versions of the `httpd` image and the Apache configuration used by Compose, located in `docker/httpd.conf`. This configuration file should contain the line `LoadModule mpm_event_module modules/mod_mpm_event.so`.

The `httpd` image was updated a couple of weeks ago, making this line mandatory for a container to run. We updated the PIM docker configuration for all 2.x branches, and it is already present in the 2.0.16 and the 2.2 alpha versions, but we still have to release the 2.1.5 that will include it. Sorry for that. It should probably be released next week.

In the meantime, you can add the configuration line like it is [in the 2.1 branch](https://github.com/akeneo/pim-community-standard/blob/2.1/docker/httpd.conf#L5). Then the `httpd` container should run without problem after you run `docker-compose up -d`.

**Comment by lferrao** [comment]
Thanks, it works!
