### ISSUE TITLE
2.2.1 - Error after upgrading

### ISSUE THREAD

**Issue by ronn0** [akeneo/pim-community-dev#7874]
I've got an error after updating to 2.2.1. 

Type error: Argument 2 passed to Akeneo\Bundle\ElasticsearchBundle\Cursor\CursorFactory::__construct() must implement interface Akeneo\Component\StorageUtils\Repository\CursorableRepositoryInterface, instance of Doctrine\ORM\EntityRepository given, called in

Can someone please help me with this. Not sure where to fix this.

**Comment by damien-carcel** [comment]
Hello @ronn0.

This is a problem of Symfony dependency injection. A service definition changed between 2.1 and 2.2, but your Symfony cache is not up to date and still use the old service definition.

Did you clear the Symfony cache and restart your FPM service? If you have one or many queue daemon running for the imports/exports, you need to stop them first, then restart FPM and finally clear the Symfony cache. Then restart the daemon(s). Otherwise, you'll have issue with PHP opcache, which can lead to your issue.

Kind regards,
Damien.

**Comment by ronn0** [comment]
Hello @damien-carcel, restart Apache did the trick for me. Thanks. Didn't expect that.

**Comment by damien-carcel** [comment]
Nice that it works :slightly_smiling_face:.
