### ISSUE TITLE
Dead Installation instructions link on README

### ISSUE THREAD

**Issue by pierre42100** [akeneo/pim-community-dev#8065]
The link for installation instruction on the main README file of the project gives the following link : https://docs.akeneo.com/2.3/install_pim/installation_ce_archive.html
but it seems to be a dead link (404 Not Found)...

**Comment by damien-carcel** [comment]
Hello @pierre42100.

Thanks for the issue. In fact, you made us realize the links are wrong since the 1.7. It is because we reorganize the documentation organization starting 1.7/2.0. But the old pages (with the old organization) are still present, so the links are still working.

However, starting 2.1, only the new organization exists, so the links lead to nothing. We'll fix it as soon as possible (if you want to contribute and made a PR on this one, do not hesitate :wink:).

Regards,
Damien.

**Comment by pierre42100** [comment]
The pull request has been merged.
