### ISSUE TITLE
Show Job Tracker for jobs run by All Users

### ISSUE THREAD

**Issue by ztruex** [akeneo/pim-community-dev#8548]
Hello,
I am trying to display jobs ran by all users on the Akeneo 2.2 UI under `Process Tracker`.  I have managed to display the `User` Column under process tracker by editing the `job_tracker.yml` but will only display jobs ran by the current user.  How to I take the restriction off that limits my view to the current user.

In the `JobExecutionRepository.php` I found a query that stated
```
if (null !== $user) {
            $qb->andWhere($qb->expr()->eq('e.user', $qb->expr()->literal($user)));
        }
```
Which I commented out the entire statement and now it shows all jobs for `Last Opertaions`, but that is only under the `Dashboard` and not `Process Tracker`.  I can't find any other statements like that one that target user for job executions.  What am I missing that is preventing my to see all operations for any user under `Process Tracker`?

**Comment by ztruex** [comment]
Hello,
Thank you so much!

**Comment by oliverde8** [comment]
To add some more information on this

Allowing all users to see all executed jobs can introduce a possible security breach as one of the reasons you can't see executions of other users is to prevent seeing the products they have exported(In the enterprise version of Akeneo you can prevent users from seeing all products).

Example: If user A has access to all exports of user B he will be able to download the files of user B and see products B can see but A should not be able to see. 

To prevent that I added a new permission, I gave that permission to users that can see all products. 

```php
<?php
class AddUsernameToGridListener extends BaseAddUsernameToGridListener
{
    public function __construct(SecurityFacade $securityFacade, TokenStorageInterface $tokenStorage)
    {
        $this->securityFacade = $securityFacade;
        parent::__construct($tokenStorage);
    }

    public function onBuildAfter(BuildAfter $event)
    {
        if (!$this->securityFacade->isGranted("pim_enrich_job_tracker_all")) {
            // User without proper grant should only see what akeneo allows by default.
            parent::onBuildAfter($event);
        }
    }
}
```

It isn't a perfect solution but in order to be able to have at least one user with the ability to monitor all jobs it was necessary.

**Comment by ztruex** [comment]
Thank you!  Do you add this into `src/Pim/Bundle/DataGridBundle/EventListener/AddUsernameToGridListener.php` or create a new file?

**Comment by oliverde8** [comment]
IMHO even if @ztruex was able to add the feature to Akeneon this ticket shouln't be closed. 
This should be a feature that's integrated to Akeneo, we had to implement it to all projects with akeneo 2+; it's the only way to have an admin easily see what's is going on. 

Users put wrong files and communicate bad errors, and being able even in production to have users to see all jobs is for me a must. Without such a functionality everytime someone complains that his import hasn't worked we need to check the logs to find the issue why a simple click would have been sufficient.

**Comment by jmleroux** [comment]
FYI, this is something we will do on our Cloud version: https://github.com/akeneo/pim-community-dev/pull/11478
