### ISSUE TITLE
Allow characters like hyphen(-) in codes

### ISSUE THREAD

**Issue by ankit-sf** [akeneo/pim-community-dev#8981]
**I'm submitting a Feature Request**
because https://www.akeneo.com/forums/forum/feature-request/ is showing closed.

Is there a possibility to allow characters like dash(-) in codes for attribute options in future?
suppose there is existing data on some e-commerce platform with attributes/categories like 
Age: 5-6, 12-15, 15+
then currently it's not possible to add dash(-), plus(+) in Akeneo codes.

**Comment by wa-daniel-fahl** [comment]
I expect this will not be possible, since akeneo reserved the hyphen for distinguishing between the actual identifier part (e.g. `color`) and parts for scope and locale (e.g. `color-ecommerce-en_US`).
This is why you can differentiate between values and codes, for example:
We have the attribute wave_length, with options `600 - 900 nm`, `900 - 1200 nm` and so on.
For the attribute option codes we use `600to900nm` and `900to1200nm`, while setting the value for de_DE to `600-900 nm`.

This is, afaik, the preferred way to solve this issue.

**Comment by ankit-sf** [comment]
@wa-daniel-fahl thanks for the explanation.
