### ISSUE TITLE
Documentation, php*mcrypt

### ISSUE THREAD

**Issue by Philippe-M** [akeneo/pim-community-dev#9021]
Hello,

In the installation documentation for Debian 9 https://docs.akeneo.com/master/install_pim/manual/system_requirements/manual_system_installation_debian9.html the list of php packages is incomplete.

With php7.1 you have to add php7.1-mcrypt and unfortunately this package is not available in php7.2.

**Comment by damien-carcel** [comment]
Hello @Philippe-M.

This is perfectly normal. Indeed `mcrypt` does not exist anymore with PHP 7.2. That's why it was removed from both the master branch of the documentation (it is not listed anymore in the [system requirements](https://docs.akeneo.com/master/install_pim/manual/system_requirements/system_requirements.html)), and the PIM requirement scripts that is launched during install (on the master branch only, which is the future 3.0 version of Akeneo PIM).

It is still required for Akeneo 2.x, which is not an issue as 2.x versions do not work with PHP 7.2, only 7.1. It is present for legacy reasons (third party extensions, for instance), but in fact it is not used anymore in the code base of Akeneo. We totally removed it from Akeneo 3.x.

I hope it answers your question.

Best regards,
Damien.

**Comment by Philippe-M** [comment]
Ok, thank's

**Comment by damien-carcel** [comment]
You're welcome.
