### ISSUE TITLE
Product : filter & search by ID 

### ISSUE THREAD

**Issue by grabelle** [akeneo/pim-community-dev#9089]
Hi,

Akeneo 2.3.15.
Could you lease explain who it is possible to get the result in attached file ??
Search by 
 ID return empry ... add a filter with the same ID gives a result !

![capture du 2018-11-09 15-29-58](https://user-images.githubusercontent.com/5048627/48268866-85441a80-e436-11e8-8118-d809f744a78f.png)

![capture du 2018-11-09 15-30-32](https://user-images.githubusercontent.com/5048627/48268938-b02e6e80-e436-11e8-9619-700e39f1d8d5.png)

Thx
Guillaume

**Comment by Delphineray** [comment]
Hello @grabelle,

Yes, I can explain to you, I think that you are using product models and variant products. 
By default, the product grid displays product models and simple products. If you use the search bar to search for a product identifier, it searches on the product models and simple products displayed in the grid so on the product models code and the simple products SKU (not on the variant products SKU that's why you have nothing in the 1st case).
When you add a SKU filter, as it's the product identifier, it forces the grid to display only products (variant products and simple products, no product models).
You can have more details in [https://help.akeneo.com/articles/enrich-products-variants.html#search-for-products-with-variants]

But we have a ticket to improve this behaviour (https://akeneo.atlassian.net/browse/IM-982), so I linked your comment.

Regards,
Delphine
