### ISSUE TITLE
AWS ElasticSearch Cluster

### ISSUE THREAD

**Issue by simonmaass** [akeneo/pim-community-dev#9154]
i am trying to get akeneo to run with an aws elastic search cluster... getting
In StaticNoPingConnectionPool.php line 51:

No alive nodes found in your cluster

In app/config/parameters.yml i changed the index_host to the aws vpc endpoint - does anyone have any idea?

**Comment by simonmaass** [comment]
I got it solved... apparently aws elasticsearch only works over port 80...

so in the parameters.yml file i had to put: "http:xxxx:80" as elasticsearch host...

found a clue here:
https://laracasts.com/discuss/channels/tips/aws-elasticsearch-uses-port-80

**Comment by amitvkhajanchi** [comment]
I had similar issue.... however, the solution was different. I had to use following:

#config.yml
....
index_hosts: 'https:{amazon elasticsearch endpoint}:443'

I couldn't get it to work with 9200 or 80.   because endpoint is on https, I had to use port 443 to get it to work.  The way I tested if connection was good to debug was:

curl -X GET '{https://amazon elasticsearch endpoint}/_all' to see if this connected.  Once I verfied this, I knew it was the config parameters I need to tweak as EC2 was connecting to Elasticsearch directly and my security groups and setting was all fine.
