### ISSUE TITLE
Major security flaw

### ISSUE THREAD

**Issue by fjlenatz** [akeneo/pim-community-dev#9531]
Hi!

I don't know if this has been reported and solved, I'm currently using the 2.3.10 release, but when I enter to the product list, there is a request to /analytics/collect_data that shows server's info.

os_version: "Linux c11568f74a48 4.9.93-linuxkit-aufs #1 SMP Wed Jun 6 16:55:56 UTC 2018 x86_64"
php_version: "7.1.23-2+0~20181017082622.9+stretch~1.gbpab65a0"
server_version: "Apache/2.4.25 (Debian)
php_extensions

Why do you guys need that info? It's ok if it only happens in dev environment, but this also happens in prod environment.

**Comment by fjlenatz** [comment]
Any news regarding this?

**Comment by BitOne** [comment]
Hello @fjlenatz ,

We are collecting this information to better understand how Akeneo PIM is used. To give you an example, thanks to this data, we decided to switch our support from Apache mod_php to Fast CGI and FPM since version 2.0 of Akeneo PIM.
Indeed a higher number of people were using Fast CGI to run the software, and we got this information thanks to these statistics.

However, you are free to disable the bundle that collects these statistics in the Symfony kernel.

In order to do that, you can edit the `app/AppKernel.php` file and comment out the line that registers the bundle ` new Pim\Bundle\AnalyticsBundle\PimAnalyticsBundle()`. In your version (2.3.10), it's the line 82.

You then need to clean up your cache, and you're good to go.

Let us know if you have any problem disabling this bundle.
