### ISSUE TITLE
Rest API performance

### ISSUE THREAD

**Issue by kimpellikaan** [akeneo/pim-community-dev#9610]
_Akeneo version C.E. 2.3_

When querying 100 products from the rest API, responses take at least 400ms. The products have 2 attributes (SKU & Name) with 34 languages.

When querying 100 products with a lot of attributes responses can take up to 4000ms.   

This is with gzip enabled, aws elastic cluster, aws rds & aws ec2 m2.large. So according to me it's not infra.

Example:
> `{{host}}/api/rest/v1/products?locales=en_GB&limit=100&page=1&with_count=true&attributes=Name,sku`

Is there a way to improve the response times? If not, does anyone have experience with caching the API calls.

**Comment by ahocquard** [comment]
Hello,

First thing: please use the `search_after` pagination type instead of offset. Otherwise, the more you are deep in the pagination, slower it is.

https://api.akeneo.com/documentation/pagination.html#the-search-after-method

It will not improve the issue you have with performance of the API when getting the first page though.
Indeed, it is very probably not an infrastructure problem.

Unfortunately, caching the API is not really possible when exporting a list of products, as the list is dynamic (you can create and delete new products). 
Caching is efficient when fetching a resource that is static (and not changing quite often).

We will maybe improve the performance of the API in the furture by not using ORM when fetching the products, but there is no ETA.

Also, what is your use case? Where are you exporting all your data and why? What is the number of products to export? 

Is it not possible to export only the products updated since a given date in order to have delta export?

Regards,
Alexandre

**Comment by kimpellikaan** [comment]
Hi Alexandre,

Thanks for your extensive response. 

> We will maybe improve the performance of the API in the future by not using ORM when fetching the products, but there is no ETA.

This would be very nice!

> Also, what is your use case? Where are you exporting all your data and why? What is the number of products to export?

We have a headless website which is querying the API through an ESB. I had a call with our Akeneo account manager, he told me that it is not an architecture you recommend. If so, we need to explore caching options.

> Also, we don't recommend to use a remote database for the PIM.

Thanks, don't think it will speed up the response 10x times though :).


Regards,
Kim

**Comment by Xcreen** [comment]
> > Also, we don't recommend to use a remote database for the PIM.
> 
> Thanks, don't think it will speed up the response 10x times though :).

Hi Kim,
we had a Akeneo-Installation which was accessing a remote database (in the same network).
After switching to a local database-installation we really improved the performance much!
I dont know the exactly speed improvements, but it was at least 2x or 4x.

**Comment by srjwebster** [comment]
@kimpellikaan Just to chime in here, we had a similar situation to you, and ended up using a NoSQL database in front of akeneo that we could then use as a cache. This had several other advantages for us as the product API wasn't giving enough model information for use.

We then added a messenger bus service into the Symfony app so when a product is updated or deleted the cache can trigger updating that product.

If you want any information around how you might replicate that, feel free to reach out.

**Comment by ahocquard** [comment]
Also, the performance of the reading part of the products in the API is far better in version 3.2x. I will close this ticket as it is an old one, feel free to re-open it if the performance improvement done in 3.2x does not solve your problem.

@srjwebster : I'm interested to know how you handle the research (as you can do in the API) in a NoSql database as the number of index is most of the time limited. 

Regards,
Alexandre

**Comment by srjwebster** [comment]
We have a SKU that is a unique value for each product, so we index that way.

If you wanted to chat about our architecture (for Colart the company I work
for) I'd be more than happy to arrange a chat.
